# fly.toml app configuration file generated for voya-api-test on 2025-05-12T13:08:01+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'voya-api-test'
primary_region = 'fra'

[env]
  NODE_ENV = "production"
  # DATABASE_URL secret olarak Fly.io platformu tarafından sağlanacak,
  # bu yüzden buraya eklemiyoruz. Sadece NODE_ENV'i ekliyoruz.


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
