app = "voya-api-test"
primary_region = "fra"

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]] # Sağlık kontrolü
    port = 3000
    type = "http"
    interval = "15s"
    timeout = "5s"
    grace_period = "30s"
    method = "GET"
    path = "/api/v1/health" # main.ts'deki global prefix ile uyumlu olmalı
    protocol = "http"