# fly.toml
app = 'voya-api-test'
primary_region = 'fra'

[env]
  NODE_ENV = "production" # BU SATIRIN OLMASI ÇOK ÖNEMLİ

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

# [[vm]] # Bu bölüm sizde varsa kalsın
#   memory = '1gb'
#   cpu_kind = 'shared'
#   cpus = 1
