# fly.toml

app = "voya-api-test"

[build]
  # Context kök dizin, Dockerfile ise apps/api altında
  context = "."
  dockerfile = "apps/api/Dockerfile"

# …
[[services]]
  internal_port = 3000
  protocol = "tcp"

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80

  [[services.ports]]
    port = 443

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "15s"
    timeout = "2s"
    restart_limit = 0
    # Sağlık kontrolü yolunuzu kontrol edin:
    path = "/api/v1/health"
